### ISSUE TITLE
Persist doesn't maintain value after page reload

### ISSUE THREAD

**Issue by JonCanning** [starfederation/datastar#411]
```
<html>
<script type="module" src="datastar.js"></script>
<span data-bind-name data-text="name.value" data-persist="name"></span>
<button data-show="!name.value" data-on-click="name.value = getName()">Sign in</button>
<button data-show="name.value" data-on-click="name.value = ''">Sign out</button>
<script>
  const getName = () => new Date().toLocaleTimeString()
</script>
</html>
```

On first load this works, I can sign in and out. However, if I sign in and reload the page, I am signed out and cannot sign in again.

**Comment by bencroker** [comment]
Are you using the latest version 0.21.3? Note that `data-persist` takes a string, so it should read `data-persist="'name'"`.

**Comment by JonCanning** [comment]
Yes, the latest. If I change the signal name to a string, the `datastar` key is created in local storage on load but the value isn't updated.

**Comment by bencroker** [comment]
Ok thanks, we’ll look into it.

**Comment by delaneyj** [comment]
There is a combination of issues, some from you... Some on me, sorry

> `<span data-bind-name ...`

this doesn't make any sense... you can't two-way bind a span.  you are using the fact (probably by accident) data-bind tries to upsert.  please use `data-signals-name__ifmissing="''"`.  The `__ifmissing` is critical.  Otherwise you are replacing what's in localStorage with a new value.  The however `ifmissing` was broken.  Now fixed in a PR.  

Remember you can set the signal any place at or above its usage in the DOM.  In general set it in a parent element to make less confusing

> <script>const getName = () => new Date().toLocaleTimeString()</script>
while technically valid, please does use global variable on the page

```html
<html>
<script type="module" src="bundles/datastar.js"></script>
<div data-signals-name__ifmissing="''" data-persist="name">
  <span data-text="name.value" ></span>
  <button data-show="!name.value" data-on-click="name.value = new Date().toLocaleTimeString()">Sign in</button>
  <button data-show="name.value" data-on-click="name.value = ''">Sign out</button>
</div>
</html>
```

**Comment by JonCanning** [comment]
Thanks for the quick fix and the advice; should the value of `data-persist` be quoted or not?

**Comment by delaneyj** [comment]
Good question, honestly it should be quoted and actually should be an expression. Guess I have another fix to do :-) the reason why is it could be affected by other signals or other things going on in the system if that makes sense
